model_list:
  - model_name: gemini-1.5-flash
    litellm_params:
      model: gemini/gemini-1.5-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: rerank-english-v3.0
    litellm_params:
      model: rerank-english-v3.0
      api_base: https://api.cohere.com/v1
      api_key: os.environ/COHERE_API_KEY
      api_type: cohere
litellm_settings:
  set_verbose: true 
  # sets litellm.callbacks = [proxy_handler_instance]
  callbacks: custom_callbacks.proxy_handler_instance
  drop_params: True

general_settings:
  master_key: sk-1234   # Virtual key cho client gọi vào Proxy

  pass_through_endpoints:
    - path: "/v1/text-to-image"                        # Route expose ra từ LiteLLM
      target: "https://engine.prod.bria-api.com/v1/text-to-image/base/2.3"
      headers:
        Authorization: "Bearer os.environ/BRIA_API_KEY"   # Đọc key từ biến môi trường
        content-type: application/json
        accept: application/json
      forward_headers: true

  custom_auth: custom_auth.user_api_key_auth
  custom_auth_settings:
    mode: "auto" # can be 'on', 'off', 'auto' - 'auto' checks both litellm api key auth + custom auth